name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
      
      - name: Build Project
        run: npm run build
      
      = name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.token }}
          publish_branch: gh-pages
          publish_dir: ./dist
