name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Create dist directory
        run: mkdir dist

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Copy CNAME file
        run: echo "michelle-heatherly.com" > ./dist/CNAME

      - name: List dist directory contents
        run: ls -l ./dist

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist
          branch: gh-pages

      - name: Clean up
        run: rm -rf ./dist/*
